set(CMAKE_SYSTEM_NAME Linux)

if(DEFINED ENV{OPENHD_GLIDE_SYSROOT} AND NOT "$ENV{OPENHD_GLIDE_SYSROOT}" STREQUAL "")
    set(OPENHD_GLIDE_SYSROOT "$ENV{OPENHD_GLIDE_SYSROOT}")
elseif(DEFINED ENV{OPENHD_SYSROOT} AND NOT "$ENV{OPENHD_SYSROOT}" STREQUAL "")
    set(OPENHD_GLIDE_SYSROOT "$ENV{OPENHD_SYSROOT}")
else()
    message(FATAL_ERROR "OPENHD_GLIDE_SYSROOT or OPENHD_SYSROOT must point to an extracted OpenHD sysroot")
endif()
if(DEFINED ENV{OPENHD_GLIDE_CROSS_TRIPLET} AND NOT "$ENV{OPENHD_GLIDE_CROSS_TRIPLET}" STREQUAL "")
    set(OPENHD_GLIDE_CROSS_TRIPLET "$ENV{OPENHD_GLIDE_CROSS_TRIPLET}")
elseif(DEFINED ENV{OPENHD_CROSS_TRIPLET} AND NOT "$ENV{OPENHD_CROSS_TRIPLET}" STREQUAL "")
    set(OPENHD_GLIDE_CROSS_TRIPLET "$ENV{OPENHD_CROSS_TRIPLET}")
else()
    message(FATAL_ERROR "OPENHD_GLIDE_CROSS_TRIPLET or OPENHD_CROSS_TRIPLET must name the GNU cross toolchain")
endif()

if(OPENHD_GLIDE_CROSS_TRIPLET STREQUAL "aarch64-linux-gnu")
    set(CMAKE_SYSTEM_PROCESSOR aarch64)
elseif(OPENHD_GLIDE_CROSS_TRIPLET STREQUAL "arm-linux-gnueabihf")
    set(CMAKE_SYSTEM_PROCESSOR arm)
else()
    message(FATAL_ERROR "Unsupported OPENHD_GLIDE_CROSS_TRIPLET=${OPENHD_GLIDE_CROSS_TRIPLET}")
endif()
set(CMAKE_SYSROOT "${OPENHD_GLIDE_SYSROOT}")
set(OPENHD_GLIDE_CROSS_GCC_VERSION "10" CACHE STRING
    "GNU cross-compiler major version matching the Bullseye sysroot")
find_program(OPENHD_GLIDE_C_COMPILER
    NAMES "${OPENHD_GLIDE_CROSS_TRIPLET}-gcc-${OPENHD_GLIDE_CROSS_GCC_VERSION}" REQUIRED)
find_program(OPENHD_GLIDE_CXX_COMPILER
    NAMES "${OPENHD_GLIDE_CROSS_TRIPLET}-g++-${OPENHD_GLIDE_CROSS_GCC_VERSION}" REQUIRED)
set(CMAKE_C_COMPILER "${OPENHD_GLIDE_C_COMPILER}")
set(CMAKE_CXX_COMPILER "${OPENHD_GLIDE_CXX_COMPILER}")
set(CMAKE_AR "${OPENHD_GLIDE_CROSS_TRIPLET}-ar")
set(CMAKE_RANLIB "${OPENHD_GLIDE_CROSS_TRIPLET}-ranlib")
set(CMAKE_STRIP "${OPENHD_GLIDE_CROSS_TRIPLET}-strip")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

file(GLOB OPENHD_GLIDE_GCC_RUNTIME_DIRS LIST_DIRECTORIES true
    "${OPENHD_GLIDE_SYSROOT}/usr/lib/gcc/${OPENHD_GLIDE_CROSS_TRIPLET}/*")
list(FILTER OPENHD_GLIDE_GCC_RUNTIME_DIRS INCLUDE REGEX "/[0-9]+(\\.[0-9]+)*$")
list(LENGTH OPENHD_GLIDE_GCC_RUNTIME_DIRS OPENHD_GLIDE_GCC_RUNTIME_COUNT)
if(OPENHD_GLIDE_GCC_RUNTIME_COUNT EQUAL 0)
    message(FATAL_ERROR "Target GCC runtime is missing from ${OPENHD_GLIDE_SYSROOT}")
endif()
list(GET OPENHD_GLIDE_GCC_RUNTIME_DIRS 0 OPENHD_GLIDE_GCC_RUNTIME_DIR)

string(JOIN " " OPENHD_GLIDE_TARGET_LINK_FLAGS
    "-L${OPENHD_GLIDE_GCC_RUNTIME_DIR}"
    "-L${OPENHD_GLIDE_SYSROOT}/usr/lib/${OPENHD_GLIDE_CROSS_TRIPLET}"
    "-L${OPENHD_GLIDE_SYSROOT}/lib/${OPENHD_GLIDE_CROSS_TRIPLET}"
    "-Wl,-rpath-link,${OPENHD_GLIDE_SYSROOT}/usr/lib/${OPENHD_GLIDE_CROSS_TRIPLET}"
    "-Wl,-rpath-link,${OPENHD_GLIDE_SYSROOT}/lib/${OPENHD_GLIDE_CROSS_TRIPLET}"
    "-pthread")
set(CMAKE_C_FLAGS_INIT "-pthread")
set(CMAKE_CXX_FLAGS_INIT "-pthread")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${OPENHD_GLIDE_TARGET_LINK_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${OPENHD_GLIDE_TARGET_LINK_FLAGS}")

set(CMAKE_FIND_ROOT_PATH "${OPENHD_GLIDE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

find_program(OPENHD_GLIDE_HOST_PKG_CONFIG NAMES pkg-config
    PATHS /usr/bin /usr/local/bin NO_CMAKE_FIND_ROOT_PATH REQUIRED)
set(PKG_CONFIG_EXECUTABLE "${OPENHD_GLIDE_HOST_PKG_CONFIG}" CACHE FILEPATH "" FORCE)
find_program(OPENHD_GLIDE_HOST_MAKE NAMES make gmake
    PATHS /usr/bin /usr/local/bin NO_CMAKE_FIND_ROOT_PATH REQUIRED)
set(CMAKE_MAKE_PROGRAM "${OPENHD_GLIDE_HOST_MAKE}" CACHE FILEPATH "" FORCE)

set(ENV{PKG_CONFIG_SYSROOT_DIR} "${OPENHD_GLIDE_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR}
    "${OPENHD_GLIDE_SYSROOT}/usr/lib/${OPENHD_GLIDE_CROSS_TRIPLET}/pkgconfig:${OPENHD_GLIDE_SYSROOT}/usr/lib/pkgconfig:${OPENHD_GLIDE_SYSROOT}/usr/share/pkgconfig")
set(CMAKE_PREFIX_PATH "${OPENHD_GLIDE_SYSROOT}/usr")
set(CMAKE_LIBRARY_PATH
    "${OPENHD_GLIDE_GCC_RUNTIME_DIR}"
    "${OPENHD_GLIDE_SYSROOT}/usr/lib/${OPENHD_GLIDE_CROSS_TRIPLET}"
    "${OPENHD_GLIDE_SYSROOT}/lib/${OPENHD_GLIDE_CROSS_TRIPLET}"
    "${OPENHD_GLIDE_SYSROOT}/usr/lib")
set(CMAKE_INCLUDE_PATH
    "${OPENHD_GLIDE_SYSROOT}/usr/include"
    "${OPENHD_GLIDE_SYSROOT}/usr/include/${OPENHD_GLIDE_CROSS_TRIPLET}")
set(CMAKE_THREAD_LIBS_INIT "-lpthread")
set(CMAKE_HAVE_THREADS_LIBRARY 1)
set(CMAKE_USE_PTHREADS_INIT 1)
set(THREADS_PREFER_PTHREAD_FLAG ON)
